//! This crate is generated by [falocon](https://github.com/tsukinaha/falocon).

mod client;
mod error;
mod methods;
mod request;
mod route;
mod types;

pub use client::*;
pub use error::Error;
pub use methods::*;
pub use request::Request;
pub use route::*;
pub use types::*;

type Result<T> = std::result::Result<T, Error>;
