[options]
library = "Clapper"
version = "0.0"
min_cfg_version = "0.0"
target_path = "."
girs_directories = [ "../gir-files-gstreamer/", "../gir-files-gtk/", "./" ]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
    "Clapper.AudioStream",
    "Clapper.Feature",
    "Clapper.StreamType",
    "Clapper.QueueProgressionMode",
    "Clapper.DiscovererDiscoveryMode",
    "Clapper.Timeline",
    "Clapper.MarkerType",
    "Clapper.ThreadedObject",
    "Clapper.VideoStream",
    "Clapper.SubtitleStream",
    "Clapper.PlayerState",
    "Clapper.PlayerSeekMethod",
]

manual = [
    "Gst.Element",
    "Gst.Object",
    "Gio.File",
    "Gio.ListModel",
    "GLib.MainContext",
]

[[object]]
    name = "Clapper.Stream"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.Discoverer"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.MediaItem"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.Marker"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.Mpris"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.Player"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.StreamList"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.Queue"
    status = "generate"
    generate_builder = true

[[object]]
    name = "Clapper.Server"
    status = "generate"
    generate_builder = true