[package]
name = "danmakw"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"
description = "A danmaku engine for gtk4"

[dependencies]
gtk = { workspace = true, features = ["v4_22"] }
glib.workspace = true
quick-xml = { workspace = true, features = ["serialize"] }
pango.workspace = true
thiserror.workspace = true
