// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from ../gir-files-gstreamer
// from ../gir-files-gtk
// from ../libclapper-rs
// DO NOT EDIT

use glib::{bitflags::bitflags, prelude::*, translate::*};

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "ClapperGtkVideoActionMask")]
    pub struct VideoActionMask: u32 {
        #[doc(alias = "CLAPPER_GTK_VIDEO_ACTION_NONE")]
        const NONE = ffi::CLAPPER_GTK_VIDEO_ACTION_NONE as _;
        #[doc(alias = "CLAPPER_GTK_VIDEO_ACTION_REVEAL_OVERLAYS")]
        const REVEAL_OVERLAYS = ffi::CLAPPER_GTK_VIDEO_ACTION_REVEAL_OVERLAYS as _;
        #[doc(alias = "CLAPPER_GTK_VIDEO_ACTION_TOGGLE_PLAY")]
        const TOGGLE_PLAY = ffi::CLAPPER_GTK_VIDEO_ACTION_TOGGLE_PLAY as _;
        #[doc(alias = "CLAPPER_GTK_VIDEO_ACTION_TOGGLE_FULLSCREEN")]
        const TOGGLE_FULLSCREEN = ffi::CLAPPER_GTK_VIDEO_ACTION_TOGGLE_FULLSCREEN as _;
        #[doc(alias = "CLAPPER_GTK_VIDEO_ACTION_SEEK_REQUEST")]
        const SEEK_REQUEST = ffi::CLAPPER_GTK_VIDEO_ACTION_SEEK_REQUEST as _;
        #[doc(alias = "CLAPPER_GTK_VIDEO_ACTION_ANY")]
        const ANY = ffi::CLAPPER_GTK_VIDEO_ACTION_ANY as _;
    }
}

#[doc(hidden)]
impl IntoGlib for VideoActionMask {
    type GlibType = ffi::ClapperGtkVideoActionMask;

    #[inline]
    fn into_glib(self) -> ffi::ClapperGtkVideoActionMask {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::ClapperGtkVideoActionMask> for VideoActionMask {
    #[inline]
    unsafe fn from_glib(value: ffi::ClapperGtkVideoActionMask) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

impl StaticType for VideoActionMask {
    #[inline]
    #[doc(alias = "clapper_gtk_video_action_mask_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::clapper_gtk_video_action_mask_get_type()) }
    }
}

impl glib::HasParamSpec for VideoActionMask {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl glib::value::ValueType for VideoActionMask {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for VideoActionMask {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0))
    }
}

impl ToValue for VideoActionMask {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<VideoActionMask> for glib::Value {
    #[inline]
    fn from(v: VideoActionMask) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}
