// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from ..\gir-files-gstreamer
// from ..\gir-files-gtk
// from ..\libclapper-rs
// DO NOT EDIT

use glib::{prelude::*, translate::*};

glib::wrapper! {
    #[doc(alias = "ClapperGtkTogglePlayButton")]
    pub struct TogglePlayButton(Object<ffi::ClapperGtkTogglePlayButton, ffi::ClapperGtkTogglePlayButtonClass>) @extends gtk::Button, gtk::Widget, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget, gtk::Actionable;

    match fn {
        type_ => || ffi::clapper_gtk_toggle_play_button_get_type(),
    }
}

impl TogglePlayButton {
    #[doc(alias = "clapper_gtk_toggle_play_button_new")]
    pub fn new() -> TogglePlayButton {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_none(ffi::clapper_gtk_toggle_play_button_new()).unsafe_cast()
        }
    }
}

impl Default for TogglePlayButton {
    fn default() -> Self {
        Self::new()
    }
}
