[package]
name = "example"
edition.workspace = true
version.workspace = true

[dependencies]
libadwaita = "0.6"
gtk4 = "0.8"
clapper = { path = "../libclapper-rs" }
clapper-gtk = { path = "../libclapper-gtk-rs" }
