// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from ..\gir-files-gstreamer
// from ..\gir-files-gtk
// DO NOT EDIT

use crate::ffi;

glib::wrapper! {
    #[doc(alias = "ClapperFeature")]
    pub struct Feature(Object<ffi::ClapperFeature, ffi::ClapperFeatureClass>) @extends gst::Object;

    match fn {
        type_ => || ffi::clapper_feature_get_type(),
    }
}

impl Feature {
    pub const NONE: Option<&'static Feature> = None;
}
