// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../../gir-files-gstreamer
// from ../../gir-files-gtk
// from ../../libclapper-rs
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT(CLAPPER_GTK_MAJOR_VERSION);
    PRINT_CONSTANT(CLAPPER_GTK_MICRO_VERSION);
    PRINT_CONSTANT(CLAPPER_GTK_MINOR_VERSION);
    PRINT_CONSTANT(CLAPPER_GTK_VERSION_S);
    PRINT_CONSTANT((guint) CLAPPER_GTK_VIDEO_ACTION_ANY);
    PRINT_CONSTANT((guint) CLAPPER_GTK_VIDEO_ACTION_NONE);
    PRINT_CONSTANT((guint) CLAPPER_GTK_VIDEO_ACTION_REVEAL_OVERLAYS);
    PRINT_CONSTANT((guint) CLAPPER_GTK_VIDEO_ACTION_SEEK_REQUEST);
    PRINT_CONSTANT((guint) CLAPPER_GTK_VIDEO_ACTION_TOGGLE_FULLSCREEN);
    PRINT_CONSTANT((guint) CLAPPER_GTK_VIDEO_ACTION_TOGGLE_PLAY);
    return 0;
}
