// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ..\..\gir-files-gstreamer
// from ..\..\gir-files-gtk
// from ..\..\libclapper-rs
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "ClapperGtkBillboardClass", sizeof(ClapperGtkBillboardClass), alignof(ClapperGtkBillboardClass));
    printf("%s;%zu;%zu\n", "ClapperGtkContainer", sizeof(ClapperGtkContainer), alignof(ClapperGtkContainer));
    printf("%s;%zu;%zu\n", "ClapperGtkContainerClass", sizeof(ClapperGtkContainerClass), alignof(ClapperGtkContainerClass));
    printf("%s;%zu;%zu\n", "ClapperGtkExtraMenuButtonClass", sizeof(ClapperGtkExtraMenuButtonClass), alignof(ClapperGtkExtraMenuButtonClass));
    printf("%s;%zu;%zu\n", "ClapperGtkLeadContainer", sizeof(ClapperGtkLeadContainer), alignof(ClapperGtkLeadContainer));
    printf("%s;%zu;%zu\n", "ClapperGtkLeadContainerClass", sizeof(ClapperGtkLeadContainerClass), alignof(ClapperGtkLeadContainerClass));
    printf("%s;%zu;%zu\n", "ClapperGtkNextItemButtonClass", sizeof(ClapperGtkNextItemButtonClass), alignof(ClapperGtkNextItemButtonClass));
    printf("%s;%zu;%zu\n", "ClapperGtkPreviousItemButtonClass", sizeof(ClapperGtkPreviousItemButtonClass), alignof(ClapperGtkPreviousItemButtonClass));
    printf("%s;%zu;%zu\n", "ClapperGtkSeekBarClass", sizeof(ClapperGtkSeekBarClass), alignof(ClapperGtkSeekBarClass));
    printf("%s;%zu;%zu\n", "ClapperGtkSimpleControlsClass", sizeof(ClapperGtkSimpleControlsClass), alignof(ClapperGtkSimpleControlsClass));
    printf("%s;%zu;%zu\n", "ClapperGtkTitleHeaderClass", sizeof(ClapperGtkTitleHeaderClass), alignof(ClapperGtkTitleHeaderClass));
    printf("%s;%zu;%zu\n", "ClapperGtkTitleLabelClass", sizeof(ClapperGtkTitleLabelClass), alignof(ClapperGtkTitleLabelClass));
    printf("%s;%zu;%zu\n", "ClapperGtkToggleFullscreenButtonClass", sizeof(ClapperGtkToggleFullscreenButtonClass), alignof(ClapperGtkToggleFullscreenButtonClass));
    printf("%s;%zu;%zu\n", "ClapperGtkTogglePlayButtonClass", sizeof(ClapperGtkTogglePlayButtonClass), alignof(ClapperGtkTogglePlayButtonClass));
    printf("%s;%zu;%zu\n", "ClapperGtkVideoActionMask", sizeof(ClapperGtkVideoActionMask), alignof(ClapperGtkVideoActionMask));
    printf("%s;%zu;%zu\n", "ClapperGtkVideoClass", sizeof(ClapperGtkVideoClass), alignof(ClapperGtkVideoClass));
    return 0;
}
