// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../../gir-files-gstreamer
// from ../../gir-files-gtk
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "ClapperAudioStreamClass", sizeof(ClapperAudioStreamClass), alignof(ClapperAudioStreamClass));
    printf("%s;%zu;%zu\n", "ClapperDiscovererClass", sizeof(ClapperDiscovererClass), alignof(ClapperDiscovererClass));
    printf("%s;%zu;%zu\n", "ClapperDiscovererDiscoveryMode", sizeof(ClapperDiscovererDiscoveryMode), alignof(ClapperDiscovererDiscoveryMode));
    printf("%s;%zu;%zu\n", "ClapperFeature", sizeof(ClapperFeature), alignof(ClapperFeature));
    printf("%s;%zu;%zu\n", "ClapperFeatureClass", sizeof(ClapperFeatureClass), alignof(ClapperFeatureClass));
    printf("%s;%zu;%zu\n", "ClapperMarkerClass", sizeof(ClapperMarkerClass), alignof(ClapperMarkerClass));
    printf("%s;%zu;%zu\n", "ClapperMarkerType", sizeof(ClapperMarkerType), alignof(ClapperMarkerType));
    printf("%s;%zu;%zu\n", "ClapperMediaItemClass", sizeof(ClapperMediaItemClass), alignof(ClapperMediaItemClass));
    printf("%s;%zu;%zu\n", "ClapperMprisClass", sizeof(ClapperMprisClass), alignof(ClapperMprisClass));
    printf("%s;%zu;%zu\n", "ClapperPlayerClass", sizeof(ClapperPlayerClass), alignof(ClapperPlayerClass));
    printf("%s;%zu;%zu\n", "ClapperPlayerSeekMethod", sizeof(ClapperPlayerSeekMethod), alignof(ClapperPlayerSeekMethod));
    printf("%s;%zu;%zu\n", "ClapperPlayerState", sizeof(ClapperPlayerState), alignof(ClapperPlayerState));
    printf("%s;%zu;%zu\n", "ClapperQueueClass", sizeof(ClapperQueueClass), alignof(ClapperQueueClass));
    printf("%s;%zu;%zu\n", "ClapperQueueProgressionMode", sizeof(ClapperQueueProgressionMode), alignof(ClapperQueueProgressionMode));
    printf("%s;%zu;%zu\n", "ClapperServerClass", sizeof(ClapperServerClass), alignof(ClapperServerClass));
    printf("%s;%zu;%zu\n", "ClapperStream", sizeof(ClapperStream), alignof(ClapperStream));
    printf("%s;%zu;%zu\n", "ClapperStreamClass", sizeof(ClapperStreamClass), alignof(ClapperStreamClass));
    printf("%s;%zu;%zu\n", "ClapperStreamListClass", sizeof(ClapperStreamListClass), alignof(ClapperStreamListClass));
    printf("%s;%zu;%zu\n", "ClapperStreamType", sizeof(ClapperStreamType), alignof(ClapperStreamType));
    printf("%s;%zu;%zu\n", "ClapperSubtitleStreamClass", sizeof(ClapperSubtitleStreamClass), alignof(ClapperSubtitleStreamClass));
    printf("%s;%zu;%zu\n", "ClapperThreadedObject", sizeof(ClapperThreadedObject), alignof(ClapperThreadedObject));
    printf("%s;%zu;%zu\n", "ClapperThreadedObjectClass", sizeof(ClapperThreadedObjectClass), alignof(ClapperThreadedObjectClass));
    printf("%s;%zu;%zu\n", "ClapperTimelineClass", sizeof(ClapperTimelineClass), alignof(ClapperTimelineClass));
    printf("%s;%zu;%zu\n", "ClapperVideoStreamClass", sizeof(ClapperVideoStreamClass), alignof(ClapperVideoStreamClass));
    return 0;
}
