use std::{
    collections::BTreeMap,
    env,
    ffi::OsStr,
    fs,
    path::{
        Path,
        PathBuf,
    },
    process::Command,
};

const APP_RESOURCE_PREFIX: &str = "/io/github/mutsumiuniverse/mutsumi";

fn main() {
    let project_root =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set"));
    let blueprint_dir = project_root.join("resources/blueprints");
    let icon_dir = project_root.join("resources/icons");
    let ui_dir = project_root.join("resources/ui");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", blueprint_dir.display());
    println!("cargo:rerun-if-changed={}", icon_dir.display());

    let blueprint_inputs = collect_files_recursive(&blueprint_dir)
        .into_iter()
        .filter(|path| path.extension().and_then(OsStr::to_str) == Some("blp"))
        .collect::<Vec<_>>();
    let icon_inputs = collect_files_recursive(&icon_dir);

    cleanup_generated_ui_files(&ui_dir);
    let ui_outputs = compile_blp(&blueprint_dir, &ui_dir, &blueprint_inputs);
    generate_gresource_xml(&project_root, &ui_dir, &ui_outputs, &icon_inputs);
    glib_compile_resource();
}

fn glib_compile_resource() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));
    // The .ui files and manifest are generated by this script, so they must not
    // become rerun-if-changed inputs as they would with glib-build-tools.
    let output = Command::new("glib-compile-resources")
        .arg("--sourcedir")
        .arg("resources")
        .arg("--target")
        .arg(out_dir.join("mutsumi.gresource"))
        .arg("resources/resources.gresource.xml")
        .output()
        .expect("Failed to execute glib-compile-resources");

    if !output.status.success() {
        panic!(
            "glib-compile-resources failed with {}:\n{}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

fn collect_files_recursive(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    if !dir.is_dir() {
        return files;
    }
    fn inner(dir: &Path, files: &mut Vec<PathBuf>) {
        let entries = fs::read_dir(dir)
            .unwrap_or_else(|e| panic!("Failed to read directory {}: {e}", dir.display()));

        entries.into_iter().for_each(|v| {
            let path = v
                .unwrap_or_else(|e| panic!("failed to read entry in {}: {e}", dir.display()))
                .path();
            if path.is_file() {
                files.push(path);
            } else if path.is_dir() {
                inner(&path, files);
            }
        });
    }
    inner(dir, &mut files);
    files.sort();
    files
}

fn compile_blp(input_dir: &Path, output_dir: &Path, inputs: &[PathBuf]) -> Vec<PathBuf> {
    if inputs.is_empty() {
        return Vec::new();
    }

    let status = Command::new("blueprint-compiler")
        .arg("batch-compile")
        .arg(output_dir)
        .arg(input_dir)
        .args(inputs)
        .status()
        .expect("Failed to execute blueprint-compiler");

    if !status.success() {
        panic!(
            "blueprint-compiler failed for {} with {status}\noutput directory: {}",
            input_dir.display(),
            output_dir.display()
        );
    }

    collect_files_recursive(output_dir)
        .into_iter()
        .filter(|path| path.extension().and_then(OsStr::to_str) == Some("ui"))
        .collect()
}

fn cleanup_generated_ui_files(ui_dir: &Path) {
    if ui_dir.exists() {
        fs::remove_dir_all(ui_dir).expect("Failed to remove UI output directory");
    }
    fs::create_dir_all(ui_dir).expect("Failed to create UI output directory");
}

fn generate_gresource_xml(
    project_root: &Path, ui_dir: &Path, ui_outputs: &[PathBuf], icon_inputs: &[PathBuf],
) {
    let output_path = project_root.join("resources/resources.gresource.xml");
    let resources_root = project_root.join("resources");

    let mut xml = String::new();
    xml.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    xml.push_str("<!-- Auto-generated by build.rs. Do not edit manually. -->\n");
    xml.push_str("<gresources>\n");

    write_icon_gresources(&mut xml, &resources_root, icon_inputs);
    write_ui_gresource(&mut xml, &resources_root, ui_dir, ui_outputs);

    xml.push_str("</gresources>\n");

    let old = fs::read_to_string(&output_path).ok();
    if old.as_deref() != Some(xml.as_str()) {
        fs::write(&output_path, xml)
            .unwrap_or_else(|e| panic!("Failed to write {}: {e}", output_path.display()));
    }
}

fn write_icon_gresources(xml: &mut String, resources_root: &Path, icon_inputs: &[PathBuf]) {
    let mut groups: BTreeMap<String, Vec<&PathBuf>> = BTreeMap::new();

    for icon in icon_inputs {
        let rel_to_resources = icon
            .strip_prefix(resources_root)
            .unwrap_or_else(|_| panic!("Icon path is not under resources/: {}", icon.display()));

        let parent = rel_to_resources.parent().unwrap_or_else(|| {
            panic!(
                "Icon path has no parent under resources/: {}",
                rel_to_resources.display()
            )
        });

        let prefix = format!("{APP_RESOURCE_PREFIX}/{}/", to_unix_path(parent));
        groups.entry(prefix).or_default().push(icon);
    }

    for (prefix, files) in groups {
        xml.push_str(&format!(
            "  <gresource prefix=\"{}\">\n",
            xml_escape_attr(&prefix)
        ));

        for icon in files {
            let rel_to_resources = icon.strip_prefix(resources_root).unwrap_or_else(|_| {
                panic!("Icon path is not under resources/: {}", icon.display())
            });

            let alias = rel_to_resources
                .file_name()
                .and_then(OsStr::to_str)
                .unwrap_or_else(|| {
                    panic!("Invalid icon file name: {}", rel_to_resources.display())
                });

            let rel_text = to_unix_path(rel_to_resources);

            if icon.extension().and_then(OsStr::to_str) == Some("svg") {
                xml.push_str(&format!(
                    "    <file preprocess=\"xml-stripblanks\" alias=\"{}\">{}</file>\n",
                    xml_escape_attr(alias),
                    xml_escape_text(&rel_text)
                ));
            } else {
                xml.push_str(&format!(
                    "    <file alias=\"{}\">{}</file>\n",
                    xml_escape_attr(alias),
                    xml_escape_text(&rel_text)
                ));
            }
        }

        xml.push_str("  </gresource>\n");
    }
}

fn write_ui_gresource(
    xml: &mut String, resources_root: &Path, ui_dir: &Path, ui_outputs: &[PathBuf],
) {
    xml.push_str(&format!(
        "  <gresource prefix=\"{}/ui/\">\n",
        APP_RESOURCE_PREFIX
    ));

    for compiled in ui_outputs {
        let rel_to_resources = compiled.strip_prefix(resources_root).unwrap_or_else(|_| {
            panic!(
                "Compiled UI path is not under resources/: {}",
                compiled.display()
            )
        });

        let rel_text = to_unix_path(rel_to_resources);

        let alias = to_unix_path(
            compiled
                .strip_prefix(ui_dir)
                .expect("Compiled UI path is not under the UI output directory"),
        );

        xml.push_str(&format!(
            "    <file compressed=\"true\" preprocess=\"xml-stripblanks\" alias=\"{}\">{}</file>\n",
            xml_escape_attr(&alias),
            xml_escape_text(&rel_text)
        ));
    }

    xml.push_str("  </gresource>\n");
}

fn to_unix_path(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn xml_escape_attr(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

fn xml_escape_text(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            _ => out.push(ch),
        }
    }
    out
}
