name: Linux
on:
  workflow_call:

jobs:
  build:
    name: Build (${{ matrix.platform }})

    strategy:
      matrix:
        include:
          - platform: amd64
            os: ubuntu-latest
          - platform: arm64
            os: ubuntu-24.04-arm

    container:
      image: ubuntu:plucky

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y git
          apt-get install -y --no-install-recommends build-essential curl gettext pkg-config libssl-dev libgtk-4-dev \
          libadwaita-1-dev libmpv-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
          libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev gstreamer1.0-libav \
          sccache

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Build tsukimi for ${{ matrix.platform }}
        env:
          RUSTC_WRAPPER: sccache
          DANDANAPI_SECRET_KEY: ${{ secrets.DANDANAPI_SECRET_KEY }}
        run: |
          echo $DANDANAPI_SECRET_KEY > secret/key
          cargo build --release --locked

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: tsukimi-${{ matrix.platform }}-linux
          path: |
            target/release/tsukimi
            i18n/locale
            resources/moe*.xml
