name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "**/.gitignore"
      - "**/.dockerignore"
      - "LICENSE"
      - "**/*.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "**/.gitignore"
      - "**/.dockerignore"
      - "LICENSE"
      - "**/*.md"

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
    secrets: inherit

  linux:
    name: Linux
    uses: ./.github/workflows/build_linux.yml
    secrets: inherit

  artifacts:
    name: Artifacts
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/artifacts.yml
    needs: [linux]
    secrets: inherit
