name: Clippy check
on: 
  workflow_call:

jobs:
  check:
    name: Lint
    runs-on: ubuntu-26.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential curl gettext pkg-config libssl-dev libgtk-4-dev \
          libadwaita-1-dev libmpv-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
          libgstreamer-plugins-base1.0-dev libgstreamer-plugins-extra1.0-dev gstreamer1.0-libav blueprint-compiler

      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache: false
          rustflags: ""

      - name: Install nightly toolchain
        run: rustup toolchain install nightly --component rustfmt

      - name: Lint
        run: |
          echo "testing" > secret/key
          cargo +nightly fmt --check
          cargo clippy --no-deps --release --all-targets
