name: Clippy check
on: 
  workflow_call:

jobs:
  clippy_check:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ubuntu:resolute
    steps:
      - name: Setup Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y git
          apt-get install -y --no-install-recommends build-essential curl gettext pkg-config libssl-dev libgtk-4-dev \
          libadwaita-1-dev libmpv-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
          libgstreamer-plugins-base1.0-dev libgstreamer-plugins-extra1.0-dev gstreamer1.0-libav clang lld

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache: false
          rustflags: "-Clinker=clang -Clink-arg=-fuse-ld=lld"

      - name: Install nightly toolchain
        run: rustup toolchain install nightly --component rustfmt

      - name: Lint
        run: |
          echo "testing" > secret/key
          cargo +nightly fmt --check
          cargo clippy --no-deps --release --all-targets
